### PR TITLE
Fractal docs

### PR DESCRIPTION
**Pull request by Jonic**
Replaces Storybook with Fractal for pattern library docs.

https://fractal-docs--sauce-design-system.netlify.app/

### CODE REVIEW

**Comment by DanielBrierton** [comment]
The preview isn't working for me.

**Comment by Jonic** [comment]
@DanielBrierton Yeah I'm debugging that now - didn't think you'd have jumped on the review so quickly, sorry!

**Comment by DanielBrierton** [comment]
All I've done so far is click the preview link 😅

**Comment by Jonic** [comment]
@DanielBrierton Sorted it now - all good!

**Review by DanielBrierton — APPROVED** [review]

**Pull request merged**
